refactor: api templates improvements
Nuxify/seline pull request #5
Opened 2024-10-31 05:11 UTC by danvincent11

2024-10-31 06:28 UTC, kabaluyot requested changes

2024-10-31 06:28 UTC, kabaluyot commented on src/lib/core/domain/repository/social.repository.ts
> +	GetPostComments(postId: number): Promise<APIResponse<CommentResponse[]>>
add comments for interface methods (all)

2024-10-31 06:28 UTC, kabaluyot commented on src/lib/servicecontainer.ts
> +export const ILocalStorageRepository: LocalStorageRepositoryInterface = new LocalStorageRepository()
sakto ngiyang sang left side boy (current changes), ngawn sang other projects ta ing outdated

2024-10-31 06:28 UTC, kabaluyot commented on src/lib/core/infrastructures/repository/social.repository.ts
> +	public async GetAllPosts(): Promise<APIResponse<PostResponse[]>> {
sakto da ngawn `GetPosts`

2024-10-31 06:28 UTC, kabaluyot commented on src/lib/core/infrastructures/repository/social.repository.ts
> +	public async GetAllPosts(): Promise<APIResponse<PostResponse[]>> {
apply to all

2024-10-31 06:28 UTC, kabaluyot commented on src/routes/+page.svelte
> +		const getAllPostsSubscription = socialAPI.getAllPostsStore.subscribe((getAllPostsState) => {
getPostsSubscription

2024-10-31 07:39 UTC, danvincent11 commented on src/lib/servicecontainer.ts
> +export const ILocalStorageRepository: LocalStorageRepositoryInterface = new LocalStorageRepository()
done

2024-10-31 07:42 UTC, danvincent11 commented on src/lib/core/infrastructures/repository/social.repository.ts
> +	public async GetAllPosts(): Promise<APIResponse<PostResponse[]>> {
done

2024-10-31 07:43 UTC, danvincent11 commented on src/routes/+page.svelte
> +		const getAllPostsSubscription = socialAPI.getAllPostsStore.subscribe((getAllPostsState) => {
done

2024-10-31 08:03 UTC, danvincent11 commented on src/lib/core/domain/repository/social.repository.ts
> +	GetPostComments(postId: number): Promise<APIResponse<CommentResponse[]>>
done

2024-10-31 13:23 UTC, kabaluyot requested changes

2024-10-31 13:23 UTC, kabaluyot commented on src/lib/core/domain/repository/social.repository.ts
> +import type { APIResponse } from '../models/dto'
use full path import

2024-11-04 15:31 UTC, danvincent11 commented on src/lib/core/domain/repository/social.repository.ts
> +import type { APIResponse } from '../models/dto'
done

2024-11-04 16:26 UTC, kabaluyot approved these changes
LGTM

2024-11-04 16:26 UTC, merged